add_executable(resource-broker-coordinator coordinator.cpp)
target_link_libraries(resource-broker-coordinator PRIVATE ResourceBroker::resourcebroker ws2_32)
if(MSVC)
    target_compile_options(resource-broker-coordinator PRIVATE /W4 /WX /EHsc)
else()
    target_compile_options(resource-broker-coordinator PRIVATE -Wall -Wextra -Werror)
endif()


add_executable(resource-broker cli.cpp)
target_link_libraries(resource-broker PRIVATE ResourceBroker::resourcebroker)
if(MSVC)
    target_compile_options(resource-broker PRIVATE /W4 /WX /EHsc)
else()
    target_compile_options(resource-broker PRIVATE -Wall -Wextra -Werror)
endif()

add_executable(resource-broker-worker worker.cpp)
target_link_libraries(resource-broker-worker PRIVATE ResourceBroker::resourcebroker ws2_32)
if(MSVC)
    target_compile_options(resource-broker-worker PRIVATE /W4 /WX /EHsc)
else()
    target_compile_options(resource-broker-worker PRIVATE -Wall -Wextra -Werror)
endif()
